# Generated by Django 4.2.11 on 2024-07-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='street',
            unique_together={('name', 'city_id')},
        ),
    ]
